name: r-pipeline
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Show repo tree & sizes (debug)
        run: |
          pwd
          ls -lah
          echo "---- tree depth 2 ----"
          find . -maxdepth 2 -type d -print
          echo "---- data listing ----"
          if [ -d data ]; then ls -lah data | head -n 200; fi
          echo "---- sample of mtx files ----"
          find data -type f -name "*_matrix*.mtx.gz" | head -n 20 || true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system libs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Run R script (capture log)
        env:
          DATA_DIR: data
          OUTPUT_DIR: docs
        run: |
          mkdir -p docs
          Rscript scRNA_OCP_full_pipeline.R --data_dir "${DATA_DIR}" --out_dir "${OUTPUT_DIR}" 2>&1 | tee docs/run.log

      # Always upload what we have in docs/ (plots, csv, run.log, sessionInfo)
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scRNA_results
          path: docs

