name: scRNA-seq OCP pipeline

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.R'
      - '.github/workflows/**.yml'
      - 'GSE*_RAW.tar*'
      - 'data/**'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: scrna-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout (with Git LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Git LFS pull (ensure large files are present)
        run: git lfs pull

      - name: Show repository tree (top level)
        run: |
          pwd
          ls -lah

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'
          use-public-rspm: true

      - name: Cache R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          # 不強制預裝所有相依；腳本會自動安裝缺的
          extra-packages: |
            any::optparse
            any::Seurat
            any::SeuratObject
            any::matrixStats
            any::clue
            any::patchwork
            any::readr
            any::dplyr
            any::ggplot2
            any::ggrepel
            any::future

      - name: Run scRNA pipeline (QUICK confirm → FULL)
        env:
          DATA_DIR: .
          OUTPUT_DIR: docs
          QUICK: "1"               # 1=先快跑確認，通過再全量；0=直接全量
          MIN_OCP: "100"
          MIN_OC: "100"
          STRICT_FAIL: "0"         # 0=記 error.txt 但不中斷；1=遇錯即失敗
          DO_DOUBLET: "1"          # 開啟雙元細胞檢測（scDblFinder/MAD）
          DO_HARMONY: "0"          # 1=用 Harmony（需 BATCH_KEY）
          DO_ANCHOR: "0"           # 1=用 Seurat anchors（需 BATCH_KEY）
          BATCH_KEY: "donor"       # 依你的 meta 欄位改成 donor/sample/batch
          DO_PSEUDOBULK: "1"       # 有 donor 時做 pseudobulk DE
          PSEUDO_MIN_CELLS: "50"
          DO_ENRICH: "0"           # 全量完成後是否做 GO 富集
          DO_TRAJECTORY: "0"       # 是否做 Slingshot（較花時間）
        run: |
          Rscript scRNA_OCP_full_pipeline.R --data_dir . --out_dir docs

      - name: List outputs
        if: always()
        run: |
          echo "== docs ==" && ls -lah docs || true
          echo "== plots ==" && ls -lah docs/plots || true
          echo "== error log ==" && (test -f docs/_error.txt && cat docs/_error.txt || echo "(no _error.txt)")

      - name: Upload results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scRNA-results-${{ github.run_number }}
          path: |
            docs/**
          if-no-files-found: warn
