name: r-pipeline
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Show repo tree & check data (debug)
        run: |
          echo "PWD:"; pwd
          echo "List top-level:"; ls -lah
          echo "Search *_matrix*.mtx.gz under repo root:"
          find . -type f -name "*_matrix*.mtx.gz" -printf "%p\t%s bytes\n" | head -n 50 || true

      - uses: r-lib/actions/setup-r@v2

      - name: Install system libs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Run R script (capture log)
        env:
          DATA_DIR: .       # ★ 你說資料放在主目錄，這裡改成「.」
          OUTPUT_DIR: docs
          STRICT_FAIL: "0"  # ★ 關閉嚴格模式（警告但不 exit 1）
        run: |
          mkdir -p docs
          Rscript scRNA_OCP_full_pipeline.R \
            --data_dir "${DATA_DIR}" \
            --out_dir  "${OUTPUT_DIR}" 2>&1 | tee docs/run.log

      - name: Print summary if present
        run: |
          if [ -f docs/_summary.json ]; then
            echo "===== SUMMARY ====="
            cat docs/_summary.json
          else
            echo "No summary file."
          fi

      # 即使失敗也把 docs/ 打包，讓你下載 run.log / 圖片 / CSV
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scRNA_results
          path: docs


